import pyfiglet
import os
import time
os.system('clear')
print("\033[1;33;40m \n")
ascii_banner = pyfiglet.figlet_format("funlookup")
print(ascii_banner)
print("\033[1;32;40m \n")
print('my data')
print('')
print('')
print('press "enter" to start')
print('')
answer = input()
os.system('clear')
time.sleep(3)
print("\033[1;33;40m \n")
ascii_banner = pyfiglet.figlet_format("funlookup")
print(ascii_banner)
print("\033[1;32;40m \n")
time.sleep(2)
print('')
print('')
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
print('your ip:')
print(s.getsockname()[0])
